import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Local dev vault path
const PLUGIN_DIR = "tests/obsidian/ColoredTagsWrangler-TestVault/.obsidian/plugins/colored-tags-wrangler";
const PLUGIN_FILES = ["main.js", "manifest.json", "styles.css"];

function copyToVault() {
    try {
        // Create plugin directory if it doesn't exist
        if (!fs.existsSync(PLUGIN_DIR)) {
            fs.mkdirSync(PLUGIN_DIR, { recursive: true });
        }

        // Copy plugin files
        for (const file of PLUGIN_FILES) {
            if (fs.existsSync(file)) {
                fs.copyFileSync(file, path.join(PLUGIN_DIR, file));
            }
        }

        console.log(`[vault] Copied plugin files to ${PLUGIN_DIR}`);
    } catch (e) {
        console.error(`[vault] Failed to copy files:`, e.message);
    }
}

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtinModules,
    ],
    format: "cjs",
    target: "es2021",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
    minify: prod,
    plugins: [
        {
            name: "copy-to-vault",
            setup(build) {
                build.onEnd(() => {
                    copyToVault();
                });
            },
        },
    ],
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
