name: BETA Obsidian plugin

on:
    push:
        tags:
            - "[0-9]+.[0-9]+.[0-9]+-BETA-*"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout development branch
                uses: actions/checkout@v3
                with:
                    ref: development  # Ensures we build from the development branch

            -   name: Use Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: "18.x"

            -   name: Build plugin
                run: |
                    npm install
                    npm run build

            -   name: Create release
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: |
                    tag="${GITHUB_REF#refs/tags/}"
                    
                    gh release create "$tag" \
                      --draft \
                      --title="$tag" \
                      main.js manifest.json styles.css
